server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  thymeleaf:
    prefix: classpath:/frontend/
  web:
    resources:
      static-locations: classpath:/frontend/
mybatis:
  config-location: classpath:/mybatis-config.xml



