ALTER TABLE addresses ADD CONSTRAINT FK_ADDRESS_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id) ON DELETE CASCADE;

ALTER TABLE work_time ADD CONSTRAINT FK_WORK_TIME_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id) ON DELETE CASCADE;

ALTER TABLE authorities ADD CONSTRAINT FK_AUTHORITIES_ON_USER FOREIGN KEY (username) REFERENCES users(username)

