insert into addresses (employee_id, address, region, district) values (1, '51282 Westport Circle', 'Brazil', 'BR');
insert into addresses (employee_id, address, region, district) values (2, '7 Division Trail', 'Portugal', 'PT');
insert into addresses (employee_id, address, region, district) values (3, '0 Valley Edge Street', 'Greece', 'GR');
insert into addresses (employee_id, address, region, district) values (4, '5695 Mcbride Parkway', 'Philippines', 'PH');
insert into addresses (employee_id, address, region, district) values (5, '357 Hermina Place', 'Taiwan', 'TW');
insert into addresses (employee_id, address, region, district) values (6, '9 Bay Place', 'Canada', 'CA');
insert into addresses (employee_id, address, region, district) values (7, '272 Lawn Street', 'Uganda', 'UG');
insert into addresses (employee_id, address, region, district) values (8, '0023 Bluestem Crossing', 'Poland', 'PL');
insert into addresses (employee_id, address, region, district) values (9, '33853 West Parkway', 'Sweden', 'SE');
insert into addresses (employee_id, address, region, district) values (10, '6798 Lien Terrace', 'Canada', 'CA');
insert into addresses (employee_id, address, region, district) values (11, '18 Harper Way', 'China', 'CN');
insert into addresses (employee_id, address, region, district) values (12, '8425 Pankratz Circle', 'China', 'CN');
insert into addresses (employee_id, address, region, district) values (13, '021 Forster Hill', 'Bangladesh', 'BD');
insert into addresses (employee_id, address, region, district) values (14, '426 Sutteridge Park', 'China', 'CN');
insert into addresses (employee_id, address, region, district) values (15, '1829 Vernon Crossing', 'Philippines', 'PH');
insert into addresses (employee_id, address, region, district) values (16, '66 Summit Pass', 'China', 'CN');
insert into addresses (employee_id, address, region, district) values (17, '59 Delaware Drive', 'China', 'CN');
insert into addresses (employee_id, address, region, district) values (18, '38258 Evergreen Park', 'Vietnam', 'VN');
insert into addresses (employee_id, address, region, district) values (19, '80 Doe Crossing Parkway', 'Kuwait', 'KW');
insert into addresses (employee_id, address, region, district) values (20, '0515 Hayes Hill', 'Argentina', 'AR');
insert into addresses (employee_id, address, region, district) values (21, '3 Village Green Street', 'Indonesia', 'ID');
insert into addresses (employee_id, address, region, district) values (22, '120 Mitchell Circle', 'Indonesia', 'ID');
insert into addresses (employee_id, address, region, district) values (23, '9 Hermina Lane', 'Ukraine', 'UA');
insert into addresses (employee_id, address, region, district) values (24, '22 Kinsman Alley', 'Mongolia', 'MN');
insert into addresses (employee_id, address, region, district) values (25, '41 Evergreen Road', 'Nepal', 'NP');
insert into addresses (employee_id, address, region, district) values (26, '9 Welch Drive', 'Brazil', 'BR');
insert into addresses (employee_id, address, region, district) values (27, '462 Glendale Terrace', 'Sweden', 'SE');
insert into addresses (employee_id, address, region, district) values (28, '9692 Portage Lane', 'China', 'CN');
insert into addresses (employee_id, address, region, district) values (29, '82917 Bultman Alley', 'China', 'CN');
insert into addresses (employee_id, address, region, district) values (30, '7 Sutherland Court', 'Latvia', 'LV');
insert into addresses (employee_id, address, region, district) values (31, '13 Oxford Pass', 'North Korea', 'KP');
insert into addresses (employee_id, address, region, district) values (32, '5 Ohio Lane', 'China', 'CN');
insert into addresses (employee_id, address, region, district) values (33, '0 Schlimgen Lane', 'Czech Republic', 'CZ');
insert into addresses (employee_id, address, region, district) values (34, '733 Ridgeview Trail', 'China', 'CN');
insert into addresses (employee_id, address, region, district) values (35, '524 Sunfield Lane', 'Russia', 'RU');
insert into addresses (employee_id, address, region, district) values (36, '4 Clyde Gallagher Trail', 'Czech Republic', 'CZ');
insert into addresses (employee_id, address, region, district) values (37, '797 Sage Avenue', 'Brazil', 'BR');
insert into addresses (employee_id, address, region, district) values (38, '80 Kipling Lane', 'Denmark', 'DK');
insert into addresses (employee_id, address, region, district) values (39, '351 Morning Center', 'Peru', 'PE');
insert into addresses (employee_id, address, region, district) values (40, '5400 Lindbergh Street', 'Macedonia', 'MK');
insert into addresses (employee_id, address, region, district) values (41, '89329 Lakewood Gardens Circle', 'Indonesia', 'ID');
insert into addresses (employee_id, address, region, district) values (42, '96841 Nelson Lane', 'Luxembourg', 'LU');
insert into addresses (employee_id, address, region, district) values (43, '646 Corry Point', 'Libya', 'LY');
insert into addresses (employee_id, address, region, district) values (44, '9887 Hoffman Hill', 'Canada', 'CA');
insert into addresses (employee_id, address, region, district) values (45, '125 Arkansas Plaza', 'Japan', 'JP');
insert into addresses (employee_id, address, region, district) values (46, '6 Harbort Pass', 'Albania', 'AL');
insert into addresses (employee_id, address, region, district) values (47, '258 Jana Circle', 'China', 'CN');
insert into addresses (employee_id, address, region, district) values (48, '56 Texas Plaza', 'El Salvador', 'SV');
insert into addresses (employee_id, address, region, district) values (49, '2684 Prentice Center', 'Egypt', 'EG');
insert into addresses (employee_id, address, region, district) values (50, '8224 Forest Run Parkway', 'Afghanistan', 'AF');
insert into addresses (employee_id, address, region, district) values (51, '14534 Mayfield Hill', 'China', 'CN');
insert into addresses (employee_id, address, region, district) values (52, '869 Paget Road', 'China', 'CN');
insert into addresses (employee_id, address, region, district) values (53, '5 Helena Avenue', 'Brazil', 'BR');
insert into addresses (employee_id, address, region, district) values (54, '68470 Westend Road', 'Philippines', 'PH');
insert into addresses (employee_id, address, region, district) values (55, '92584 Lien Drive', 'Sweden', 'SE');
insert into addresses (employee_id, address, region, district) values (56, '2 Transport Road', 'Indonesia', 'ID');
insert into addresses (employee_id, address, region, district) values (57, '8807 Merry Street', 'Philippines', 'PH');
insert into addresses (employee_id, address, region, district) values (58, '744 Shoshone Street', 'Mexico', 'MX');
insert into addresses (employee_id, address, region, district) values (59, '81 Judy Lane', 'Russia', 'RU');
insert into addresses (employee_id, address, region, district) values (60, '85 Debra Road', 'China', 'CN');
insert into addresses (employee_id, address, region, district) values (61, '4110 Crownhardt Alley', 'China', 'CN');
insert into addresses (employee_id, address, region, district) values (62, '2 Lyons Point', 'Sweden', 'SE');
insert into addresses (employee_id, address, region, district) values (63, '83282 Randy Parkway', 'Brazil', 'BR');
insert into addresses (employee_id, address, region, district) values (64, '9 Reinke Way', 'Peru', 'PE');
insert into addresses (employee_id, address, region, district) values (65, '737 Pierstorff Court', 'Poland', 'PL');
insert into addresses (employee_id, address, region, district) values (66, '5091 Crest Line Road', 'France', 'FR');
insert into addresses (employee_id, address, region, district) values (67, '4110 Old Shore Place', 'China', 'CN');
insert into addresses (employee_id, address, region, district) values (68, '8952 Menomonie Crossing', 'Tanzania', 'TZ');
insert into addresses (employee_id, address, region, district) values (69, '96 Derek Pass', 'Colombia', 'CO');
insert into addresses (employee_id, address, region, district) values (70, '8 Namekagon Parkway', 'Portugal', 'PT');
insert into addresses (employee_id, address, region, district) values (71, '00 Linden Avenue', 'Indonesia', 'ID');
insert into addresses (employee_id, address, region, district) values (72, '3229 Prairieview Circle', 'China', 'CN');
insert into addresses (employee_id, address, region, district) values (73, '29 Bartelt Crossing', 'Philippines', 'PH');
insert into addresses (employee_id, address, region, district) values (74, '52046 Springs Plaza', 'Poland', 'PL');
insert into addresses (employee_id, address, region, district) values (75, '96973 Vidon Junction', 'Indonesia', 'ID');
insert into addresses (employee_id, address, region, district) values (76, '60534 School Drive', 'China', 'CN');
insert into addresses (employee_id, address, region, district) values (77, '0147 Manley Place', 'Brazil', 'BR');
insert into addresses (employee_id, address, region, district) values (78, '8258 Waubesa Crossing', 'Indonesia', 'ID');
insert into addresses (employee_id, address, region, district) values (79, '18297 Express Hill', 'Italy', 'IT');
insert into addresses (employee_id, address, region, district) values (80, '8 Vermont Circle', 'Azerbaijan', 'AZ');
insert into addresses (employee_id, address, region, district) values (81, '11600 Morning Drive', 'China', 'CN');
insert into addresses (employee_id, address, region, district) values (82, '7266 Morningstar Street', 'Bosnia and Herzegovina', 'BA');
insert into addresses (employee_id, address, region, district) values (83, '502 Hudson Street', 'Indonesia', 'ID');
insert into addresses (employee_id, address, region, district) values (84, '381 Riverside Terrace', 'Indonesia', 'ID');
insert into addresses (employee_id, address, region, district) values (85, '6 Northwestern Terrace', 'China', 'CN');
insert into addresses (employee_id, address, region, district) values (86, '69 Burning Wood Street', 'Poland', 'PL');
insert into addresses (employee_id, address, region, district) values (87, '462 Eagan Pass', 'China', 'CN');
insert into addresses (employee_id, address, region, district) values (88, '84687 Welch Plaza', 'China', 'CN');
insert into addresses (employee_id, address, region, district) values (89, '893 Magdeline Circle', 'Switzerland', 'CH');
insert into addresses (employee_id, address, region, district) values (90, '9 Chinook Circle', 'Philippines', 'PH');
insert into addresses (employee_id, address, region, district) values (91, '05790 Acker Hill', 'Indonesia', 'ID');
insert into addresses (employee_id, address, region, district) values (92, '0011 Manley Alley', 'China', 'CN');
insert into addresses (employee_id, address, region, district) values (93, '95886 Almo Plaza', 'China', 'CN');
insert into addresses (employee_id, address, region, district) values (94, '027 Colorado Court', 'Poland', 'PL');
insert into addresses (employee_id, address, region, district) values (95, '992 Kings Point', 'Philippines', 'PH');
insert into addresses (employee_id, address, region, district) values (96, '7 Glacier Hill Lane', 'Indonesia', 'ID');
insert into addresses (employee_id, address, region, district) values (97, '8512 Shoshone Pass', 'Russia', 'RU');
insert into addresses (employee_id, address, region, district) values (98, '67 Milwaukee Terrace', 'Portugal', 'PT');
insert into addresses (employee_id, address, region, district) values (99, '34 Fieldstone Place', 'Thailand', 'TH');
insert into addresses (employee_id, address, region, district) values (100, '26 Canary Crossing', 'Sudan', 'SD');